/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { StrategyService } from "../strategy.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StrategyCreateInput } from "./StrategyCreateInput";
import { Strategy } from "./Strategy";
import { StrategyFindManyArgs } from "./StrategyFindManyArgs";
import { StrategyWhereUniqueInput } from "./StrategyWhereUniqueInput";
import { StrategyUpdateInput } from "./StrategyUpdateInput";
import { ResultFindManyArgs } from "../../result/base/ResultFindManyArgs";
import { Result } from "../../result/base/Result";
import { ResultWhereUniqueInput } from "../../result/base/ResultWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class StrategyControllerBase {
  constructor(
    protected readonly service: StrategyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Strategy })
  @nestAccessControl.UseRoles({
    resource: "Strategy",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createStrategy(
    @common.Body() data: StrategyCreateInput
  ): Promise<Strategy> {
    return await this.service.createStrategy({
      data: {
        ...data,

        gameSession: data.gameSession
          ? {
              connect: data.gameSession,
            }
          : undefined,

        player: data.player
          ? {
              connect: data.player,
            }
          : undefined,

        scenario: data.scenario
          ? {
              connect: data.scenario,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,

        gameSession: {
          select: {
            id: true,
          },
        },

        id: true,

        player: {
          select: {
            id: true,
          },
        },

        scenario: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Strategy] })
  @ApiNestedQuery(StrategyFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Strategy",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async strategies(@common.Req() request: Request): Promise<Strategy[]> {
    const args = plainToClass(StrategyFindManyArgs, request.query);
    return this.service.strategies({
      ...args,
      select: {
        createdAt: true,
        description: true,

        gameSession: {
          select: {
            id: true,
          },
        },

        id: true,

        player: {
          select: {
            id: true,
          },
        },

        scenario: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Strategy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Strategy",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async strategy(
    @common.Param() params: StrategyWhereUniqueInput
  ): Promise<Strategy | null> {
    const result = await this.service.strategy({
      where: params,
      select: {
        createdAt: true,
        description: true,

        gameSession: {
          select: {
            id: true,
          },
        },

        id: true,

        player: {
          select: {
            id: true,
          },
        },

        scenario: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Strategy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Strategy",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateStrategy(
    @common.Param() params: StrategyWhereUniqueInput,
    @common.Body() data: StrategyUpdateInput
  ): Promise<Strategy | null> {
    try {
      return await this.service.updateStrategy({
        where: params,
        data: {
          ...data,

          gameSession: data.gameSession
            ? {
                connect: data.gameSession,
              }
            : undefined,

          player: data.player
            ? {
                connect: data.player,
              }
            : undefined,

          scenario: data.scenario
            ? {
                connect: data.scenario,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,

          gameSession: {
            select: {
              id: true,
            },
          },

          id: true,

          player: {
            select: {
              id: true,
            },
          },

          scenario: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Strategy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Strategy",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteStrategy(
    @common.Param() params: StrategyWhereUniqueInput
  ): Promise<Strategy | null> {
    try {
      return await this.service.deleteStrategy({
        where: params,
        select: {
          createdAt: true,
          description: true,

          gameSession: {
            select: {
              id: true,
            },
          },

          id: true,

          player: {
            select: {
              id: true,
            },
          },

          scenario: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/results")
  @ApiNestedQuery(ResultFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Result",
    action: "read",
    possession: "any",
  })
  async findResults(
    @common.Req() request: Request,
    @common.Param() params: StrategyWhereUniqueInput
  ): Promise<Result[]> {
    const query = plainToClass(ResultFindManyArgs, request.query);
    const results = await this.service.findResults(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        outcome: true,

        strategy: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/results")
  @nestAccessControl.UseRoles({
    resource: "Strategy",
    action: "update",
    possession: "any",
  })
  async connectResults(
    @common.Param() params: StrategyWhereUniqueInput,
    @common.Body() body: ResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      results: {
        connect: body,
      },
    };
    await this.service.updateStrategy({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/results")
  @nestAccessControl.UseRoles({
    resource: "Strategy",
    action: "update",
    possession: "any",
  })
  async updateResults(
    @common.Param() params: StrategyWhereUniqueInput,
    @common.Body() body: ResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      results: {
        set: body,
      },
    };
    await this.service.updateStrategy({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/results")
  @nestAccessControl.UseRoles({
    resource: "Strategy",
    action: "update",
    possession: "any",
  })
  async disconnectResults(
    @common.Param() params: StrategyWhereUniqueInput,
    @common.Body() body: ResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      results: {
        disconnect: body,
      },
    };
    await this.service.updateStrategy({
      where: params,
      data,
      select: { id: true },
    });
  }
}
